from os import system

def bienvenida_screen():
    system("cls")
    print("**************************************************************************************")
    print("                                                                                      ")
    print("              ▂▃▄▅▆▇█▓▒░ SISTEMAS TICKET SHOW ░▒▓█▇▆▅▄▃▂                      ")
    print("                                                                                      ")
    print("**************************************************************************************")
    print("                                                                                      ")
    print("   Bienvenido a SISTEMAS TICKET SHOW                                                  ")
    print("                                                                                      ")
    print("                                                                                      ")
    print("   Por favor para continuar seleccione una opcion:                                    ")
    print("                                                                                      ")
    print("                                                                                      ")
    print("   1- Crear usuario                                                                   ")
    print("   2- Iniciar sesion                                                                  ")
    print("   3- Salir                                                                           ")
    print("                                                                                      ")
    print("                                                                                      ")

def crear_usuario_screen():
    system("cls")
    print("**************************************************************************************")
    print("                                                                                      ")
    print("              ▂▃▄▅▆▇█▓▒░ SISTEMAS TICKET SHOW ░▒▓█▇▆▅▄▃▂                      ")
    print("                                                                                      ")
    print("                                CREAR USUARIO                                         ")
    print("                                                                                      ")
    print("**************************************************************************************")
    print("                                                                                      ")
    print("   Para poder operar en nuestra plataforma es necesario que cree un usuario           ")
    print("   y contraseña                                                                       ")
    print("                                                                                      ")
    print("   Por favor a continuacion brinde un correo electronico y una contraseña             ")
    print("   La contraseña debe estar formada por:                                              ")
    print("     - 8 caracteres                                                                   ")
    print("     - La primer letra mayuscula                                                      ")
    print("     - Al menos 1 caracter numerico                                                   ")
    print("     - Al menos 1 caracter especial (# & - _ ! %)                                     ")
    print("                                                                                      ")
    print("                                                                                      ")


def selecionar_ubicacion_screen():
    system("cls")
    print("**************************************************************************************")
    print("                                                                                      ")
    print("              ▂▃▄▅▆▇█▓▒░ SISTEMAS TICKET SHOW ░▒▓█▇▆▅▄▃▂                      ")
    print("                                                                                      ")
    print("                            SELECCION DE UBICACIONES                                  ")
    print("                                                                                      ")
    print("**************************************************************************************")
    print("                                                                                      ")
    print("   ╔════════════════════════════════════════════════════════════════════════════╗     ")
    print("                          S    T    A    G    E                                       ")
    print("   ╚════════════════════════════════════════════════════════════════════════════╝     ")
    print("                                                                                      ")
    print("                                                                                      ")